---
{{if .Values._000_commonConfig.kafkatopicupdater.enabled}}

kind: Secret
apiVersion: v1
metadata:
  name: {{include "united-manufacturing-hub.fullname" .}}-kafkatopicupdater-secrets
  labels:
    {{- include "united-manufacturing-hub.labels.kafkatopicupdater" . | nindent 4}}
type: Opaque
stringData:
  ca.crt: |
    {{.Values._000_commonConfig.certificates.CACert | nindent 4}}
  tls.crt: |
    {{.Values._000_commonConfig.certificates.kafkatopicupdater.sslCertificatePem | nindent 4}}
  tls.key: |
    {{.Values._000_commonConfig.certificates.kafkatopicupdater.sslKeyPem | nindent 4}}

{{end}}
