---
{{if .Values._000_commonConfig.datasources.cameraconnect.enabled}}

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{include "united-manufacturing-hub.fullname" .}}-cameraconnect
  labels:
    {{- include "united-manufacturing-hub.labels.cameraconnect" . | nindent 4}}
    app.kubernetes.io/component: "cameraconnect"
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "united-manufacturing-hub.labels.cameraconnect" . | nindent 6}}
      app.kubernetes.io/component: "cameraconnect"
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        {{- include "united-manufacturing-hub.labels.cameraconnect" . | nindent 8}}
        app.kubernetes.io/component: "cameraconnect"
    spec:
      hostNetwork: true
      volumes:
        - name: storage
          emptyDir: {}
        - name: cameraconnect-gentlproducer
          hostPath:
            path: /home/rancher/genicam_producer
      initContainers:
        - args:
            - mkdir -p /app/assets/producer_files && cp -u /genTLProducer/files.zip /app/assets/ && unzip -n /app/assets/files.zip -d /app/assets/producer_files
          command:
            - /bin/sh
            - -c
          image: busybox
          name: init-cameraconnect-gentlproducer
          volumeMounts:
            - mountPath: /app/assets
              name: storage
            - mountPath: /genTLProducer
              name: cameraconnect-gentlproducer
      containers:
        - name: {{include "united-manufacturing-hub.fullname" .}}-cameraconnect
          {{if .Values.cameraconnect.tag}}
          image: {{.Values.cameraconnect.image}}:{{.Values.cameraconnect.tag}}
          {{- else}}
          image: {{.Values.cameraconnect.image}}:{{.Chart.AppVersion}}
          {{end}}
          resources:
            limits:
              cpu: {{if .Values.cameraconnect.resources.limits}}
              {{.Values.cameraconnect.resources.limits.cpu | default "100m"}}
              {{else}}
              100m
              {{end}}
              memory: {{if .Values.cameraconnect.resources.limits}}
              {{.Values.cameraconnect.resources.limits.memory | default "100Mi"}}
              {{else}}
              100Mi
              {{end}}
            requests:
              cpu: {{if .Values.cameraconnect.resources.requests}}
              {{.Values.cameraconnect.resources.requests.cpu | default "10m"}}
              {{else}}
              10m
              {{end}}
              memory: {{if .Values.cameraconnect.resources.requests}}
              {{.Values.cameraconnect.resources.requests.memory | default "25Mi"}}
              {{else}}
              25Mi
              {{end}}
          volumeMounts:
            - mountPath: /app/assets
              name: storage
          env:
            - name: CUBE_TRANSMITTERID
              value: {{.Values._000_commonConfig.serialNumber | default "default" | quote}}
            - name: BROKER_URL
              value: {{.Values._000_commonConfig.mqttBridge.remoteBrokerURL | default "ssl://united-manufacturing-hub-vernemq-local-service.united-manufacturing-hub:8883"}}
            - name: BROKER_PORT #TODO: remove this !
            - name: TRIGGER
              value: {{.Values._000_commonConfig.datasources.cameraconnect.trigger | default "MQTT" | quote}}
            - name: ACQUISITION_DELAY
              value: {{.Values._000_commonConfig.datasources.cameraconnect.acquisitionDelay | default "0.0" | quote}}
            - name: CYCLE_TIME
              value: {{.Values._000_commonConfig.datasources.cameraconnect.cycleTime | default "4" | quote}}
            - name: CAMERA_INTERFACE
              value: {{.Values._000_commonConfig.datasources.cameraconnect.cameraInterface | default "GenICam" | quote}}
            - name: IMAGE_WIDTH
              value: {{.Values._000_commonConfig.datasources.cameraconnect.imageWidth | default "800" | quote}}
            - name: IMAGE_HEIGHT
              value: {{.Values._000_commonConfig.datasources.cameraconnect.imageHeight | default "800" | quote}}
            - name: IMAGE_CHANNELS
              value: {{.Values._000_commonConfig.datasources.cameraconnect.imageChannels | default "3" | quote}}
            - name: MAC_ADDRESS
              value: {{.Values._000_commonConfig.datasources.cameraconnect.macAddress | default "02-2625A-09849" | quote}}
            - name: EXPOSURE_TIME
              value: {{.Values._000_commonConfig.datasources.cameraconnect.exposureTime | default "1000" | quote}}
            - name: EXPOSURE_AUTO
              value: {{.Values._000_commonConfig.datasources.cameraconnect.exposureAuto | default "Off" | quote}}
            - name: PIXEL_FORMAT
              value: {{.Values._000_commonConfig.datasources.cameraconnect.pixelFormat | default "Mono8" | quote}}
            - name: LOGGING_LEVEL
              value: {{.Values.cameraconnect.loggingLevel | default "INFO" | quote}}
            - name: DEFAULT_GENTL_PRODUCER_PATH
              value: "/app/assets/producer_files"
      serviceAccountName: {{include "united-manufacturing-hub.serviceAccountName" .}}
      restartPolicy: Always

{{end}}
