---
{{if or .Values.factoryinsight.enabled .Values._000_commonConfig.datastorage.enabled}}

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{include "united-manufacturing-hub.fullname" .}}-factoryinsight-deployment
  labels:
    {{- include "united-manufacturing-hub.labels.factoryinsight" . | nindent 4}}
  {{if .Values.factoryinsight.annotations}}
  annotations:
    {{- toYaml .Values.factoryinsight.annotations | nindent 4}}
  {{end}}
spec:
  replicas: {{.Values.factoryinsight.replicas | default 2}}
  selector:
    matchLabels:
     {{- include "united-manufacturing-hub.labels.factoryinsight" . | nindent 6}}
  strategy:
    type: RollingUpdate
  template:
    metadata:
      name: {{include "united-manufacturing-hub.fullname" .}}-factoryinsight
      labels:
        {{- include "united-manufacturing-hub.labels.factoryinsight" . | nindent 8}}
        redis-client: "true"
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 1
              podAffinityTerm:
                labelSelector:
                  matchLabels:
                    name: {{include "united-manufacturing-hub.fullname" .}}-factoryinsight
                topologyKey: "kubernetes.io/hostname"
      containers:
        - name: {{include "united-manufacturing-hub.fullname" .}}-factoryinsight
          {{if .Values.factoryinsight.image.tag}}
          image: {{.Values.factoryinsight.image.repository}}:{{.Values.factoryinsight.image.tag}}
          {{- else}}
          image: {{.Values.factoryinsight.image.repository}}:{{.Chart.AppVersion}}
          {{end}}
          imagePullPolicy: {{.Values.factoryinsight.image.pullPolicy | default "IfNotPresent"}}
          ports:
              - name: http
                containerPort: 80
                protocol: TCP
          resources:
            limits:
              cpu: {{if .Values.factoryinsight.resources.limits}}
              {{.Values.factoryinsight.resources.limits.cpu | default "1000m"}}
              {{else}}
              1000m
              {{end}}
            requests:
              cpu: {{if .Values.factoryinsight.resources.requests}}
              {{.Values.factoryinsight.resources.requests.cpu | default "200m"}}
              {{else}}
              200m
              {{end}}
          env:
            - name: LOGGING_LEVEL
              value: PRODUCTION
            - name: REDIS_URI
              value: {{.Values.factoryinsight.redis.URI1 | default "united-manufacturing-hub-redis-node-0.united-manufacturing-hub-redis-headless:26379"}}
            - name: REDIS_URI2
              value: {{.Values.factoryinsight.redis.URI2 | default "united-manufacturing-hub-redis-node-1.united-manufacturing-hub-redis-headless:26379"}}
            - name: REDIS_URI3
              value: {{.Values.factoryinsight.redis.URI3 | default "united-manufacturing-hub-redis-node-2.united-manufacturing-hub-redis-headless:26379"}}
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: redis-secret
                  key: redispassword

            - name: POSTGRES_HOST
              value: {{.Values.factoryinsight.db_host | default "united-manufacturing-hub"}}
            - name: POSTGRES_PORT
              value: {{.Values.factoryinsight.db_port | default 5432 | quote}}
            - name: POSTGRES_DATABASE
              value: {{.Values.factoryinsight.db_database | default "factoryinsight"}}
            - name: POSTGRES_USER
              value: {{.Values.factoryinsight.db_user | default "factoryinsight"}}
            - name: POSTGRES_PASSWORD
              value: {{.Values._000_commonConfig.datastorage.db_password | default "changeme"}}

              {{$index := 1}}
              {{range $customerName, $password := .Values.customers | default dict}}
            - name: CUSTOMER_NAME_{{$index}}
              value: {{$customerName}}
            - name: CUSTOMER_PASSWORD_{{$index}}
              value: {{$password}}
              {{$index = add $index 1}}
              {{end}}

            - name: FACTORYINSIGHT_USER
              value: {{.Values.factoryinsight.user | default "factoryinsight"}}
            - name: FACTORYINSIGHT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: factoryinsight-secret
                  key: password
            - name: VERSION
              value: "1"

          livenessProbe:
            httpGet:
              path: /live
              port: 8086
            periodSeconds: 5
          startupProbe:
            httpGet:
              path: /live
              port: 8086
            periodSeconds: 10
            failureThreshold: 5 # 5*periodSeconds (10) => 50 sec max startup time

          # define a readiness probe that checks every 15 seconds
          readinessProbe:
            httpGet:
              path: /ready
              port: 8086
            periodSeconds: 1

      restartPolicy: Always
      terminationGracePeriodSeconds: 300 # the longest requests can up to 4 minutes
{{end}}
