---
{{if and .Values.automigrate.enabled .Values._000_commonConfig.datastorage.enabled}}

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{include "united-manufacturing-hub.fullname" .}}-automigrate
  labels:
    {{- include "united-manufacturing-hub.labels.automigrate" . | nindent 4}}
  {{if .Values.automigrate.annotations}}
  annotations:
    {{- toYaml .Values.automigrate.annotations | nindent 4}}
  {{end}}
spec:
  replicas: 1 # Never increase this !
  selector:
    matchLabels:
      name: {{include "united-manufacturing-hub.fullname" .}}-automigrate
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        name: {{include "united-manufacturing-hub.fullname" .}}-automigrate
        {{- include "united-manufacturing-hub.labels.automigrate" . | nindent 8}}
    spec:
      priorityClassName: high-priority-automigrate # kill other pods if necessary
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 1
              podAffinityTerm:
                labelSelector:
                  matchLabels:
                    name: {{include "united-manufacturing-hub.fullname" .}}-automigrate
                topologyKey: "kubernetes.io/hostname"
      # Be nice to the db
      terminationGracePeriodSeconds: 180
      containers:
        - name: {{include "united-manufacturing-hub.fullname" .}}-automigrate
          {{if .Values.automigrate.image.tag}}
          image: {{.Values.automigrate.image.repository}}:{{.Values.automigrate.image.tag}}
          {{- else}}
          image: {{.Values.automigrate.image.repository}}:{{.Chart.AppVersion}}
          {{end}}
          imagePullPolicy: {{.Values.automigrate.image.pullPolicy}}
          volumeMounts:
            - name: {{include "united-manufacturing-hub.fullname" .}}-automigrate-certificates
              mountPath: /SSL_certs
              readOnly: true
          ports:
            - name: metrics
              containerPort: 2112
              protocol: TCP
            - name: pprof
              containerPort: 1337
              protocol: TCP
          env:

            - name: POSTGRES_HOST
              value: {{.Values.factoryinsight.db_host}}
            - name: POSTGRES_DATABASE
              value: {{.Values.factoryinsight.db_database}}
            - name: PATRONI_SUPERUSER_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{include "united-manufacturing-hub.fullname" .}}-credentials
                  key: PATRONI_SUPERUSER_PASSWORD
            - name: VERSION
              value: {{.Chart.Version}}

            - name: LOGGING_LEVEL
              value: PRODUCTION

            - name: MY_POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name


          # define a liveness probe that checks every 5 seconds, starting after 5 seconds
          livenessProbe:
            httpGet:
              path: /live
              port: 8086
            periodSeconds: 5
            initialDelaySeconds: 5
          startupProbe:
            httpGet:
              path: /live
              port: 8086
            periodSeconds: 10
            failureThreshold: 5 # 5*periodSeconds (10) => 50 sec max startup time

          resources:
            limits:
              cpu: {{.Values.automigrate.resources.limits.cpu}}
              memory: {{.Values.automigrate.resources.limits.memory}}
            requests:
              cpu: {{.Values.automigrate.resources.requests.cpu}}
              memory: {{.Values.automigrate.resources.requests.memory}}
      volumes:
        - name: {{include "united-manufacturing-hub.fullname" .}}-automigrate-certificates
          secret:
            secretName: {{include "united-manufacturing-hub.fullname" .}}-automigrate-secrets

      serviceAccountName: ""
      restartPolicy: Always
{{end}}

