---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{include "united-manufacturing-hub.fullname" .}}-metrics
spec:
  schedule: {{ .Values.metrics.cronJob.schedule }}
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: {{include "united-manufacturing-hub.fullname" .}}-metrics-cron
              image: {{.Values.metrics.image.repository}}:{{.Chart.AppVersion}}
              imagePullPolicy: {{ .Values.metrics.image.pullPolicy }}
          restartPolicy: OnFailure
