---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{include "united-manufacturing-hub.fullname" .}}-metrics
spec:
  schedule: {{ .Values.metrics.cronJob.schedule }}
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: {{include "united-manufacturing-hub.fullname" .}}-metrics-cron
              {{if .Values.kafkabridge.image.tag}}
              image: {{.Values.metrics.image.repository}}:{{.Values.metrics.image.tag}}
              {{- else}}
              image: {{.Values.metrics.image.repository}}:{{.Chart.AppVersion}}
              {{end}}
              imagePullPolicy: {{ .Values.metrics.image.pullPolicy }}
          restartPolicy: OnFailure
