---
{{if or .Values.mqttbridge.enabled .Values._000_commonConfig.mqttBridge.enabled}}

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{include "united-manufacturing-hub.fullname" .}}-mqttbridge
  labels:
    {{- include "united-manufacturing-hub.labels.mqttbridge" . | nindent 4}}
spec:
  serviceName: {{include "united-manufacturing-hub.fullname" .}}-mqttbridge
  replicas: 1
  selector:
    matchLabels:
      {{- include "united-manufacturing-hub.labels.mqttbridge" . | nindent 6}}
  template:
    metadata:
      labels:
        {{- include "united-manufacturing-hub.labels.mqttbridge" . | nindent 8}}
    spec:
      containers:
      - name: {{include "united-manufacturing-hub.fullname" .}}-mqttbridge
        {{if .Values.mqttbridge.tag}}
        image: {{.Values.mqttbridge.image}}:{{.Values.mqttbridge.tag}}
        {{- else}}
        image: {{.Values.mqttbridge.image}}:{{.Chart.AppVersion}}
        {{end}}
        volumeMounts:
        - name: {{include "united-manufacturing-hub.fullname" .}}-mqttbridge-data
          mountPath: /data/queue
        - name: {{include "united-manufacturing-hub.fullname" .}}-mqttbridge-certificates
          mountPath: /SSL_certs/remote
          readOnly: true
        resources:
          limits:
            cpu: {{if .Values.mqttbridge.resources.limits}}
            {{.Values.mqttbridge.resources.limits.cpu | default "200m"}}
            {{else}}
            200m
            {{end}}
            memory: {{if .Values.mqttbridge.resources.limits}}
            {{.Values.mqttbridge.resources.limits.memory | default "100Mi"}}
            {{else}}
            100Mi
            {{end}}
          requests:
            cpu: {{if .Values.mqttbridge.resources.requests}}
            {{.Values.mqttbridge.resources.requests.cpu | default "100m"}}
            {{else}}
            100m
            {{end}}
            memory: {{if .Values.mqttbridge.resources.requests}}
            {{.Values.mqttbridge.resources.requests.memory | default "20Mi"}}
            {{else}}
            20Mi
            {{end}}
        env:
        - name: REMOTE_CERTIFICATE_NAME
          value: {{.Values._000_commonConfig.serialNumber | default "default"}}
        - name: REMOTE_BROKER_URL
          value: {{.Values._000_commonConfig.mqttBridge.remoteBrokerURL | default "ssl://united-manufacturing-hub-vernemq-local-service.united-manufacturing-hub:8883"}}
        - name: REMOTE_SUB_TOPIC
          value: {{.Values._000_commonConfig.mqttBridge.remoteSubTopic | default "ia" | quote}}
        - name: REMOTE_PUB_TOPIC
          value: {{.Values._000_commonConfig.mqttBridge.remotePubTopic | default "ia/factoryinsight"}}
        - name: REMOTE_BROKER_SSL_ENABLED
          value: {{.Values._000_commonConfig.mqttBridge.remoteBrokerSSLEnabled | default true | quote}}
        - name: LOCAL_CERTIFICATE_NAME
          value: {{.Values._000_commonConfig.mqttBridge.localCertificateName | default "LOCAL"}}
        - name: LOCAL_BROKER_URL
          value: 'mqtt://{{include "united-manufacturing-hub.fullname" .}}-vernemq:1883'
        - name: LOCAL_SUB_TOPIC
          value: {{.Values._000_commonConfig.mqttBridge.localSubTopic | default "ia/factoryinsight"}}
        - name: LOCAL_PUB_TOPIC
          value: {{.Values._000_commonConfig.mqttBridge.localPubTopic | default "ia" | quote}}
        - name: LOCAL_BROKER_SSL_ENABLED
          value: {{.Values._000_commonConfig.mqttBridge.localBrokerSSLEnabled | default false | quote}}
        - name: BRIDGE_ONE_WAY
          value: {{.Values._000_commonConfig.mqttBridge.oneWay | default true | quote}}
      volumes:
      - name: {{include "united-manufacturing-hub.fullname" .}}-mqttbridge-data
        persistentVolumeClaim:
          claimName: {{include "united-manufacturing-hub.fullname" .}}-mqttbridge-claim
      - name: {{include "united-manufacturing-hub.fullname" .}}-mqttbridge-config
        configMap:
          name: {{include "united-manufacturing-hub.fullname" .}}-mqttbridge-config
      - name: {{include "united-manufacturing-hub.fullname" .}}-mqttbridge-certificates
        secret:
          secretName: {{include "united-manufacturing-hub.fullname" .}}-mqttbridge-secrets
{{end}}
