---
{{if or .Values.barcodereader.enabled .Values._000_commonConfig.datasources.barcodereader.enabled}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{include "united-manufacturing-hub.fullname" .}}-barcodereader
  labels:
    {{- include "united-manufacturing-hub.labels.barcodereader" . | nindent 4}}
  {{if .Values.barcodereader.annotations}}
  annotations:
    {{- toYaml .Values.barcodereader.annotations | nindent 4}}
  {{end}}
spec:
  selector:
    matchLabels:
      name: {{include "united-manufacturing-hub.fullname" .}}-barcodereader
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        name: {{include "united-manufacturing-hub.fullname" .}}-barcodereader
        {{- include "united-manufacturing-hub.labels.barcodereader" . | nindent 8}}
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 1
              podAffinityTerm:
                labelSelector:
                  matchLabels:
                    name: {{include "united-manufacturing-hub.fullname" .}}-barcodereader
                topologyKey: "kubernetes.io/hostname"
      containers:
        - name: {{include "united-manufacturing-hub.fullname" .}}-barcodereader
          {{if .Values.barcodereader.image.tag}}
          image: {{.Values.barcodereader.image.repository}}:{{.Values.barcodereader.image.tag}}
          {{- else}}
          image: {{.Values.barcodereader.image.repository}}:{{.Chart.AppVersion}}
          {{end}}
          imagePullPolicy: {{.Values.barcodereader.image.pullPolicy | default "IfNotPresent"}}
          securityContext:
            privileged: true
          volumeMounts:
            - name: devs
              mountPath: /dev/
          env:
            - name: KAFKA_BOOTSTRAP_SERVER
              value: {{include "united-manufacturing-hub.fullname" .}}-kafka:9092
            - name: INPUT_DEVICE_NAME
              value: {{.Values._000_commonConfig.datasources.barcodereader.USBDeviceName | default "Datalogic ADC, Inc. Handheld Barcode Scanner" | quote}}
            - name: INPUT_DEVICE_PATH
              value: {{.Values._000_commonConfig.datasources.barcodereader.USBDevicePath | default "" | quote}}

            - name: MY_POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: CUSTOMER_ID
              value: {{.Values._000_commonConfig.datasources.barcodereader.customerID | default "raw" | quote}}
            - name: LOCATION
              value: {{.Values._000_commonConfig.datasources.barcodereader.location | default "barcodereader" | quote}}
            - name: ASSET_ID
              value: {{.Values._000_commonConfig.datasources.barcodereader.machineID | default "barcodereader" | quote}}

            - name: SERIAL_NUMBER
              value: {{.Values._000_commonConfig.serialNumber | default "default" | quote}}

            - name: SCAN_ONLY
              value: {{.Values.barcodereader.scanOnly | default "false" | quote}}

          resources:
            limits:
              cpu: {{if .Values.barcodereader.resources.limits}}
              {{.Values.barcodereader.resources.limits.cpu | default "10m"}}
              {{else}}
              10m
              {{end}}
              memory: {{if .Values.barcodereader.resources.limits}}
              {{.Values.barcodereader.resources.limits.memory | default "60Mi"}}
              {{else}}
              60Mi
              {{end}}
            requests:
              cpu: {{if .Values.barcodereader.resources.requests}}
              {{.Values.barcodereader.resources.requests.cpu | default "2m"}}
              {{else}}
              2m
              {{end}}
              memory: {{if .Values.barcodereader.resources.requests}}
              {{.Values.barcodereader.resources.requests.memory | default "30Mi"}}
              {{else}}
              30Mi
              {{end}}
      serviceAccountName: ""
      restartPolicy: Always
      volumes:
        - name: devs
          hostPath:
            path: /dev/
{{end}}

