
---
{{if .Values._000_commonConfig.infrastructure.mqtt.enabled}}

apiVersion: v1
kind: ConfigMap
metadata:
  name: {{include "united-manufacturing-hub.fullname" .}}-hivemqce
data:
  config.xml: |
{{end}}