---
{{if .Values._000_commonConfig.infrastructure.mqtt.enabled}}

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{include "united-manufacturing-hub.fullname" .}}-hivemq-ce
  labels:
    {{- include "united-manufacturing-hub.labels.hivemqce" . | nindent 4}}
    app.kubernetes.io/component: "hivemqce"
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "united-manufacturing-hub.labels.hivemqce" . | nindent 6}}
      app.kubernetes.io/component: "hivemqce"
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        {{- include "united-manufacturing-hub.labels.hivemqce" . | nindent 8}}
        app.kubernetes.io/component: "hivemqce"
    spec:
      volumes:
        - name: hivemq-ce-mqtt-config
          configMap:
            name: {{include "united-manufacturing-hub.fullname" .}}-hivemqce
      containers:
        - name: {{include "united-manufacturing-hub.fullname" .}}-hivemqce
          {{if .Values.hivemqce.tag}}
          image: {{.Values.hivemqce.image.repository}}:{{.Values.hivemqce.tag}}
          {{- else}}
          image: {{.Values.hivemqce.image.repository}}:2022.1
          {{end}}
          imagePullPolicy: {{.Values.hivemqce.image.pullPolicy}}
          resources:
            limits:
              cpu: {{.Values.hivemqce.resources.limits.cpu}}
              memory: {{.Values.hivemqce.resources.limits.memory}}
            requests:
              cpu: {{.Values.hivemqce.resources.requests.cpu}}
              memory: {{.Values.hivemqce.resources.requests.memory}}
          volumeMounts:
            - mountPath: /configs
              name: hivemq-ce-mqtt-config

{{end}}