
---
{{if .Values._000_commonConfig.infrastructure.mqtt.enabled}}

apiVersion: v1
kind: Secret
metadata:
  name: {{include "united-manufacturing-hub.fullname" .}}-hivemqce-secret-keystore
type: Opaque
stringData:
  keystore.jks: |
    {{ .Values._000_commonConfig.infrastructure.mqtt.mqtts.keystoreBase64 | b64dec }}

{{end}}