---
{{if .Values._000_commonConfig.infrastructure.mqtt.enabled}}

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{include "united-manufacturing-hub.fullname" .}}-hivemqce
  labels:
    {{- include "united-manufacturing-hub.labels.hivemqce" . | nindent 4}}
    app.kubernetes.io/component: "hivemqce"
spec:
  serviceName: {{include "united-manufacturing-hub.fullname" .}}-hivemqce
  replicas: 1
  selector:
    matchLabels:
      {{- include "united-manufacturing-hub.labels.hivemqce" . | nindent 6}}
      app.kubernetes.io/component: "hivemqce"
  template:
    metadata:
      labels:
        {{- include "united-manufacturing-hub.labels.hivemqce" . | nindent 8}}
        app.kubernetes.io/component: "hivemqce"
    spec:
      volumes:
        - name: hivemqce-mqtt-config
          configMap:
            name: {{include "united-manufacturing-hub.fullname" .}}-hivemqce
        - name: {{include "united-manufacturing-hub.fullname" .}}-hivemqce-data
          persistentVolumeClaim:
            claimName: {{include "united-manufacturing-hub.fullname" .}}-hivemqce-claim
      initContainers:
        - name: hivemqce-extension-init
          image: {{.Values.hivemqce.initContainer.hivemqextensioninit.image.repository}}:{{.Values.hivemqce.initContainer.hivemqextensioninit.image.tag}}
          imagePullPolicy: {{.Values.hivemqce.initContainer.hivemqextensioninit.image.pullPolicy}}
      containers:
        - name: {{include "united-manufacturing-hub.fullname" .}}-hivemqce
          {{if .Values.hivemqce.image.tag}}
          image: {{.Values.hivemqce.image.repository}}:{{.Values.hivemqce.image.tag}}
          {{- else}}
          image: {{.Values.hivemqce.image.repository}}:2022.1
          {{end}}
          imagePullPolicy: {{.Values.hivemqce.image.pullPolicy}}
          resources:
            limits:
              cpu: {{.Values.hivemqce.resources.limits.cpu}}
              memory: {{.Values.hivemqce.resources.limits.memory}}
            requests:
              cpu: {{.Values.hivemqce.resources.requests.cpu}}
              memory: {{.Values.hivemqce.resources.requests.memory}}
          volumeMounts:
            - mountPath: /opt/hivemq/conf # This is a symlink to /opt/hivemq-ce-VERSION/conf
              name: hivemqce-mqtt-config
            - mountPath: /opt/hivemq/conf/data
              name: {{include "united-manufacturing-hub.fullname" .}}-hivemqce-data
          ports:
            {{- if .Values.hivemqce.service.mqtt.enabled}}
            - name: mqtt
              containerPort: 1883
              protocol: TCP
            {{- end}}
            {{- if .Values.hivemqce.service.mqtts.enabled}}
            - name: mqtts
              containerPort: 8883
              protocol: TCP
            {{- end}}
            {{- if .Values.hivemqce.service.ws.enabled}}
            - name: ws
              containerPort: 8080
              protocol: TCP
            {{- end}}
            {{- if .Values.hivemqce.service.wss.enabled}}
            - name: wss
              containerPort: 8443
              protocol: TCP
            {{- end}}



{{end}}