---
{{if and .Values._000_commonConfig.infrastructure.mqtt.enabled .Values._000_commonConfig.mqttBridge.enabled}}

kind: Secret
apiVersion: v1
metadata:
  name: {{include "united-manufacturing-hub.fullname" .}}-mqttkafkabridge-kafka-secrets
  labels:
    {{- include "united-manufacturing-hub.labels.mqttkafkabridge" . | nindent 4}}
type: Opaque
data:
  ca.crt: |
    {{.Values._000_commonConfig.infrastructure.mqtt.tls.caCert | nindent 4}}
  tls.crt: |
    {{.Values._000_commonConfig.infrastructure.mqtt.tls.mqtt_kafka_bridge.cert | nindent 4}}
  tls.key: |
    {{.Values._000_commonConfig.infrastructure.mqtt.tls.mqtt_kafka_bridge.key | nindent 4}}

{{end}}
