---
{{if or .Values.grafanaproxy.enabled .Values._000_commonConfig.datainput.enabled}}
apiVersion: v1
kind: Service
metadata:
  name: {{include "united-manufacturing-hub.fullname" .}}-grafanaproxy-service
  labels:
    {{- include "united-manufacturing-hub.labels.grafanaproxy" . | nindent 4}}
  {{if .Values.grafanaproxy.service.annotations}}
  annotations:
    {{- toYaml .Values.grafanaproxy.service.annotations | nindent 4}}
  {{end}}
spec:
  type: {{.Values.grafanaproxy.service.type | default "LoadBalancer"}}
  ports:
    - port: {{.Values.grafanaproxy.service.port | default 2096}}
      targetPort: {{.Values.grafanaproxy.service.targetPort | default 80}}
      protocol: {{.Values.grafanaproxy.service.protocol | default "TCP"}}
      name: {{.Values.grafanaproxy.service.name | default "http"}}
  selector:
     {{- include "united-manufacturing-hub.labels.grafanaproxy" . | nindent 4}}

{{end}}
