name: golint
on:
  pull_request:
    branches:
      - main

permissions:
  contents: read

env:
  GH_TOKEN: ${{ secrets.GITHUB_TOKEN  }}

jobs:
  lint-and-check:
    name: Lint and Check Go code
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
        with:
          token: ${{ env.GH_TOKEN }}
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20.*'
      - name: Install vulncheck
        run: go install golang.org/x/vuln/cmd/govulncheck@latest
        working-directory: ./golang
        shell: bash
      - name: Run go vulncheck and generate report
        run: go run golang.org/x/vuln/cmd/govulncheck ./...
        working-directory: ./golang
        shell: bash
      - name: Install golangci-lint
        run: go install github.com/golangci/golangci-lint/cmd/golangci-lint@latest
        working-directory: ./golang
        shell: bash
      - name: Run golangci-lint
        run: go run github.com/golangci/golangci-lint/cmd/golangci-lint@latest run -v -c ../.golangci.yaml ./...
        working-directory: ./golang
        shell: bash
